Repository JOBLOLI/BestTeam-soen341project2023, pull requests merged in 2023-03, with the labels that each got.

#51 to realtime
  core/__pycache__/__init__.cpython-38.pyc
  core/__pycache__/settings.cpython-38.pyc
  core/__pycache__/urls.cpython-38.pyc
  core/__pycache__/wsgi.cpython-38.pyc
  db.sqlite3
  main/__pycache__/__init__.cpython-38.pyc
  main/__pycache__/urls.cpython-38.pyc
  main/__pycache__/views.cpython-38.pyc
  main/views.py
  templates/signup.html
Labels: frontend, backend

#54 admin permission
  db.sqlite3
  main/__pycache__/urls.cpython-38.pyc
  main/__pycache__/views.cpython-38.pyc
  main/urls.py
  main/views.py
  static/css/home.css
  templates/home.html
  templates/job_creation.html
Labels: frontend, backend

#70 Notifications
  core/__pycache__/__init__.cpython-38.pyc
  core/__pycache__/settings.cpython-38.pyc
  core/__pycache__/urls.cpython-38.pyc
  core/__pycache__/wsgi.cpython-38.pyc
  db.sqlite3
  docker-compose.yml
  main/__pycache__/__init__.cpython-38.pyc
  main/__pycache__/urls.cpython-38.pyc
  main/__pycache__/views.cpython-38.pyc
  main/urls.py
  main/views.py
  static/css/jobmanagepage.css
  templates/home.html
  templates/jobmanage.html
Labels: frontend, backend, bug

#72 profile editing
  db.sqlite3
  main/__pycache__/urls.cpython-38.pyc
  main/__pycache__/views.cpython-38.pyc
  main/urls.py
  main/views.py
  static/css/profile_edit.css
  templates/profile.html
  templates/profile_edit.html
Labels: frontend, backend

#73 bug fix
  db.sqlite3
  main/__pycache__/urls.cpython-38.pyc
  main/__pycache__/views.cpython-38.pyc
  main/urls.py
  main/views.py
Labels: backend, bug

#74 Admin backend 3
  core/__pycache__/__init__.cpython-311.pyc
  core/__pycache__/settings.cpython-311.pyc
  core/__pycache__/urls.cpython-311.pyc
  core/__pycache__/wsgi.cpython-311.pyc
  db.sqlite3
  main/__pycache__/__init__.cpython-311.pyc
  main/__pycache__/urls.cpython-311.pyc
  main/__pycache__/views.cpython-311.pyc
  main/views.py
  templates/admin_p.html
Labels: frontend, backend
