Repository JOBLOLI/BestTeam-soen341project2023, pull requests merged in 2023-04, with the labels that each got.

#86 Employer profile backend
  main/views.py
Labels: backend

#85 Employer UI Prototype
  .DS_Store
  db.sqlite3
  static/images/Company_logo.png
  templates/Employer_profile.html
Labels: frontend

#87 profile rating update and employer profile integration
  core/__pycache__/__init__.cpython-38.pyc
  core/__pycache__/settings.cpython-38.pyc
  core/__pycache__/urls.cpython-38.pyc
  core/__pycache__/wsgi.cpython-38.pyc
  db.sqlite3
  main/__pycache__/__init__.cpython-38.pyc
  main/__pycache__/urls.cpython-38.pyc
  main/__pycache__/views.cpython-38.pyc
  main/views.py
  templates/Employer_profile.html
  templates/profile.html
Labels: frontend, backend
